// AUTO-GENERATED FILE - DO NOT EDIT
// Run `bun run scripts/generate-asset-catalog.ts` to regenerate

import type { AssetConfig } from "./config-types.js";
import type { EnrichedPairConfig } from "./market-data-catalog.js";

export const ASSET_CATALOG: AssetConfig[] = [
    {
        symbol: "BCH",
        ledgerId: 20,
        name: "Bitcoin Cash",
        quantityDisplayDecimals: 8,
        quantityScale: 8,
    },
    {
        symbol: "BNB",
        ledgerId: 5,
        name: "BNB",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "BONK",
        ledgerId: 7,
        name: "Bonk",
        quantityDisplayDecimals: 0,
        quantityScale: 0,
    },
    {
        symbol: "BTC",
        ledgerId: 3,
        name: "Bitcoin",
        quantityDisplayDecimals: 8,
        quantityScale: 8,
    },
    {
        symbol: "CANCELONLY",
        ledgerId: 14,
        name: "Status Matrix Cancel-Only Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "DELISTED",
        ledgerId: 8,
        name: "Delisted Lifecycle Example Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "DELISTSOON",
        ledgerId: 9,
        name: "Scheduled Delisting Example Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "DISABLED",
        ledgerId: 10,
        name: "Disabled Pair Example Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "DOGE",
        ledgerId: 19,
        name: "Dogecoin",
        quantityDisplayDecimals: 8,
        quantityScale: 8,
    },
    {
        symbol: "ENABLED",
        ledgerId: 12,
        name: "Status Matrix Enabled Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "ETC",
        ledgerId: 21,
        name: "Ethereum Classic",
        quantityDisplayDecimals: 6,
        quantityScale: 18,
    },
    {
        symbol: "ETH",
        ledgerId: 6,
        name: "Ethereum",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "LISTSOON",
        ledgerId: 11,
        name: "Future Listing Example Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "LTC",
        ledgerId: 18,
        name: "Litecoin",
        quantityDisplayDecimals: 8,
        quantityScale: 8,
    },
    {
        symbol: "POSTONLY",
        ledgerId: 15,
        name: "Status Matrix Post-Only Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "REDUCEONLY",
        ledgerId: 16,
        name: "Status Matrix Reduce-Only Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "SOL",
        ledgerId: 4,
        name: "Solana",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "USDC",
        ledgerId: 2,
        name: "USD Coin",
        quantityDisplayDecimals: 4,
        quantityScale: 6,
    },
    {
        symbol: "USDT",
        ledgerId: 1,
        name: "Tether USD",
        quantityDisplayDecimals: 4,
        quantityScale: 6,
    },
    {
        symbol: "WITHDRAW_TEST_ASSET",
        ledgerId: 700007,
        name: "Withdraw Test Asset",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
    {
        symbol: "XRP",
        ledgerId: 17,
        name: "Ripple",
        quantityDisplayDecimals: 6,
        quantityScale: 6,
    },
];

export const PAIR_CATALOG: EnrichedPairConfig[] = [
    {
        symbolId: 4,
        symbol: "BNB-USDT",
        baseAsset: {
            symbol: "BNB",
            ledgerId: 5,
            name: "BNB",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.01",
        stepSize: "0.0001",
        minNotionalQuote: "1",
        minQtyBase: "0.0001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 5,
        defaultMarketSlippagePctSell: 5,
        maxClientRefDriftPct: 2,
        marketdata: {
            orderbookPriceBuckets: [0.01, 0.1, 1, 10, 100],
        },
        listingAt: 1770771356092,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 5,
        symbol: "BONK-USDT",
        baseAsset: {
            symbol: "BONK",
            ledgerId: 7,
            name: "Bonk",
            quantityDisplayDecimals: 0,
            quantityScale: 0,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.000001",
        stepSize: "1",
        minNotionalQuote: "1",
        minQtyBase: "1",
        allowBuyFeeFromReceived: true,
        defaultMarketSlippagePctBuy: 10,
        defaultMarketSlippagePctSell: 10,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [1e-8, 1e-7, 0.000001, 0.00001, 0.0001],
        },
        listingAt: 1770771356092,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 1,
        symbol: "BTC-USDT",
        baseAsset: {
            symbol: "BTC",
            ledgerId: 3,
            name: "Bitcoin",
            quantityDisplayDecimals: 8,
            quantityScale: 8,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.01",
        stepSize: "0.00001",
        minNotionalQuote: "1",
        minQtyBase: "0.00001",
        allowBuyFeeFromReceived: true,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 1,
        marketdata: {
            orderbookPriceBuckets: [0.01, 0.1, 1, 10, 100, 1000],
        },
        listingAt: 1770864956092,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 12,
        symbol: "CANCELONLY-USDT",
        baseAsset: {
            symbol: "CANCELONLY",
            ledgerId: 14,
            name: "Status Matrix Cancel-Only Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1771452049090,
        delistingAt: null,
        status: "cancel_only",
    },
    {
        symbolId: 901,
        symbol: "DELISTED-USDT",
        baseAsset: {
            symbol: "DELISTED",
            ledgerId: 8,
            name: "Delisted Lifecycle Example Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1763756209591,
        delistingAt: 1771445809591,
        status: "enabled",
    },
    {
        symbolId: 902,
        symbol: "DELISTSOON-USDT",
        baseAsset: {
            symbol: "DELISTSOON",
            ledgerId: 9,
            name: "Scheduled Delisting Example Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1770927409591,
        delistingAt: 1774124209591,
        status: "enabled",
    },
    {
        symbolId: 903,
        symbol: "DISABLED-USDT",
        baseAsset: {
            symbol: "DISABLED",
            ledgerId: 10,
            name: "Disabled Pair Example Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1770927409591,
        delistingAt: null,
        status: "disabled",
    },
    {
        symbolId: 10,
        symbol: "ENABLED-USDT",
        baseAsset: {
            symbol: "ENABLED",
            ledgerId: 12,
            name: "Status Matrix Enabled Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1771452049090,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 2,
        symbol: "ETH-USDT",
        baseAsset: {
            symbol: "ETH",
            ledgerId: 6,
            name: "Ethereum",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.01",
        stepSize: "0.0001",
        minNotionalQuote: "1",
        minQtyBase: "0.0001",
        allowBuyFeeFromReceived: true,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 1,
        marketdata: {
            orderbookPriceBuckets: [0.01, 0.1, 1, 10, 100],
        },
        listingAt: 1770771356092,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 904,
        symbol: "LISTSOON-USDT",
        baseAsset: {
            symbol: "LISTSOON",
            ledgerId: 11,
            name: "Future Listing Example Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1913919409591,
        delistingAt: null,
        status: "enabled",
    },
    {
        symbolId: 13,
        symbol: "POSTONLY-USDT",
        baseAsset: {
            symbol: "POSTONLY",
            ledgerId: 15,
            name: "Status Matrix Post-Only Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1771452049090,
        delistingAt: null,
        status: "post_only",
    },
    {
        symbolId: 14,
        symbol: "REDUCEONLY-USDT",
        baseAsset: {
            symbol: "REDUCEONLY",
            ledgerId: 16,
            name: "Status Matrix Reduce-Only Asset",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: false,
        defaultMarketSlippagePctBuy: 2,
        defaultMarketSlippagePctSell: 2,
        maxClientRefDriftPct: 5,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1771452049090,
        delistingAt: null,
        status: "reduce_only",
    },
    {
        symbolId: 3,
        symbol: "SOL-USDT",
        baseAsset: {
            symbol: "SOL",
            ledgerId: 4,
            name: "Solana",
            quantityDisplayDecimals: 6,
            quantityScale: 6,
        },
        quoteAsset: {
            symbol: "USDT",
            ledgerId: 1,
            name: "Tether USD",
            quantityDisplayDecimals: 4,
            quantityScale: 6,
        },
        tickSize: "0.001",
        stepSize: "0.001",
        minNotionalQuote: "1",
        minQtyBase: "0.001",
        allowBuyFeeFromReceived: true,
        defaultMarketSlippagePctBuy: 5,
        defaultMarketSlippagePctSell: 5,
        maxClientRefDriftPct: 2,
        marketdata: {
            orderbookPriceBuckets: [0.001, 0.01, 0.1, 1, 10],
        },
        listingAt: 1770771356092,
        delistingAt: null,
        status: "enabled",
    },
];
