// AUTO-GENERATED FILE - DO NOT EDIT
// Run `bun run refresh:catalogs:testnet` to regenerate

import type {
    ZipperEnrichedAssetConfig,
    ZipperChainConfig,
    ZipperChainContractConfig,
} from "./zipper-catalog.js";

export const ZIPPER_CHAIN_CATALOG: ZipperChainConfig[] = [
    {
        chainId: 5,
        code: "arbitrum-sepolia",
        name: "Arbitrum Sepolia",
        nativeChainId: "421614",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.arbiscan.io",
        icon: "arb.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 4,
        code: "base-sepolia",
        name: "Base Sepolia",
        nativeChainId: "84532",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.basescan.org",
        icon: "base.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 1,
        code: "bitcoin-testnet3",
        name: "Bitcoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "BTC",
        explorerUrl: "https://mempool.space/testnet",
        icon: "btc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 110,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 10,
        code: "bitcoincash-testnet",
        name: "Bitcoin Cash Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "BCH",
        explorerUrl: "https://tbch.loping.net",
        icon: "bch.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 120,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 6,
        code: "bsc-testnet",
        name: "BNB Smart Chain Testnet",
        nativeChainId: "97",
        nativeCurrencySymbol: "BNB",
        explorerUrl: "https://testnet.bscscan.com",
        icon: "bsc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 50,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 7,
        code: "doge-testnet",
        name: "Dogecoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "DOGE",
        explorerUrl: "https://doge-testnet-explorer.qed.me",
        icon: "doge.webp",
        requiredConfirmations: 5,
        confirmationTimeSeconds: 50,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 42,
    },
    {
        chainId: 11,
        code: "ethereum-classic-testnet",
        name: "Ethereum Classic Testnet",
        nativeChainId: "63",
        nativeCurrencySymbol: "ETC",
        explorerUrl: "https://etc-mordor.blockscout.com",
        icon: "etc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 2,
        code: "ethereum-sepolia",
        name: "Ethereum Sepolia",
        nativeChainId: "11155111",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.etherscan.io",
        icon: "eth.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 75,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 8,
        code: "litecoin-testnet",
        name: "Litecoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "LTC",
        explorerUrl: "https://litecoinspace.org/testnet",
        icon: "litecoin.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 50,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 888168,
        code: "polyester-staging",
        name: "Polyester Staging",
        nativeChainId: "888168",
        nativeCurrencySymbol: "POL",
        explorerUrl: "https://staging.polyesterscan.com",
        icon: "polyester.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 3,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 9,
        code: "ripple-testnet",
        name: "Ripple Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "XRP",
        explorerUrl: "https://testnet.xrpl.org/",
        icon: "ripple.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 30,
        isCaseSensitive: true,
        minAddressLength: 25,
        maxAddressLength: 46,
    },
    {
        chainId: 3,
        code: "solana-devnet",
        name: "Solana Devnet",
        nativeChainId: "",
        nativeCurrencySymbol: "SOL",
        explorerUrl: "https://solscan.io/?cluster=devnet",
        icon: "sol.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: true,
        minAddressLength: 32,
        maxAddressLength: 44,
    },
];

export const ZIPPER_ASSET_CATALOG: ZipperEnrichedAssetConfig[] = [
    {
        asset: "BCH",
        ledgerId: 20,
        name: "Bitcoin Cash",
        icon: "bch.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xa97cddf4a06bc5f21aca7e7540ef9ea0ff4f8adb9d7dbd7f6c26efb3f696abe9",
        chains: [
            {
                chainId: 10,
                code: "bitcoincash-testnet",
                name: "Bitcoin Cash Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "BCH",
                explorerUrl: "https://tbch.loping.net",
                icon: "bch.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 120,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 18,
                isNativeAsset: true,
                networkFee: "0.00003",
                networkFeeTsSec: 0,
                depositMinAmount: "0.00001",
                withdrawMinAmount: "0.00001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0xBF0BB35DD8EcBc19888398963816e7b75c2dC0C9",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "BNB",
        ledgerId: 5,
        name: "BNB",
        icon: "bnb.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x84f284b8f96a449a73a2abd6faa45f5180a36ce1925ba9b4c9683ccaa3d1178d",
        chains: [
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 11,
                isNativeAsset: true,
                networkFee: "0.0000028",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0xE9754a7133E249Bd1005A8090fcF8a207FEbF6B2",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "BTC",
        ledgerId: 3,
        name: "Bitcoin",
        icon: "btc.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0x4bac7d8baf3f4f429951de9baff555c2f70564c6a43361e09971ef219908703d",
        chains: [
            {
                chainId: 1,
                code: "bitcoin-testnet3",
                name: "Bitcoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "BTC",
                explorerUrl: "https://mempool.space/testnet",
                icon: "btc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 110,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 1,
                isNativeAsset: true,
                networkFee: "0.000025",
                networkFeeTsSec: 0,
                depositMinAmount: "0.00001",
                withdrawMinAmount: "0.00001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0x245c5e492aD3a028cFA1776a844D94F66C806494",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "DOGE",
        ledgerId: 19,
        name: "Dogecoin",
        icon: "doge.webp",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xf94adcdd39eb156b60766264ff00058b4ed540a41fcd1e3f0ef433285885f736",
        chains: [
            {
                chainId: 7,
                code: "doge-testnet",
                name: "Dogecoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "DOGE",
                explorerUrl: "https://doge-testnet-explorer.qed.me",
                icon: "doge.webp",
                requiredConfirmations: 5,
                confirmationTimeSeconds: 50,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 42,
                chainAssetId: 15,
                isNativeAsset: true,
                networkFee: "0.016",
                networkFeeTsSec: 0,
                depositMinAmount: "0.1",
                withdrawMinAmount: "0.1",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0xa6045694255EcCe43A0ca819bb6211f8Ae0132dA",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "ETC",
        ledgerId: 21,
        name: "Ethereum Classic",
        icon: "etc.svg",
        quantityScale: 18,
        quantityDisplayDecimals: 6,
        uAssetId: "0x997997d543f68c7b77e62a13efc6e546bd2a81c2aa8769c3354422ebbbb4fba4",
        chains: [
            {
                chainId: 11,
                code: "ethereum-classic-testnet",
                name: "Ethereum Classic Testnet",
                nativeChainId: "63",
                nativeCurrencySymbol: "ETC",
                explorerUrl: "https://etc-mordor.blockscout.com",
                icon: "etc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 19,
                isNativeAsset: true,
                networkFee: "0.007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x0Bb556202923a17555F1c3CbB8f088CB1E8eACD6",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "ETH",
        ledgerId: 6,
        name: "Ethereum",
        icon: "eth.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x4f5b812789fc606be1b3b16908db13fc7a9adf7ca72641f84d75b47069d3d7f0",
        chains: [
            {
                chainId: 2,
                code: "ethereum-sepolia",
                name: "Ethereum Sepolia",
                nativeChainId: "11155111",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.etherscan.io",
                icon: "eth.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 75,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 2,
                isNativeAsset: true,
                networkFee: "0.00000006",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x51ab1bc4720201bcE945b89f409299BA0cDa63F4",
                    decimals: 18,
                },
            },
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 6,
                isNativeAsset: true,
                networkFee: "0.0000004",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x1C5eb32fA66F594EE15E31e83ea1f0FdE05f9EDe",
                    decimals: 18,
                },
            },
            {
                chainId: 5,
                code: "arbitrum-sepolia",
                name: "Arbitrum Sepolia",
                nativeChainId: "421614",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.arbiscan.io",
                icon: "arb.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 9,
                isNativeAsset: true,
                networkFee: "0.0000012",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x9b40A0C16759b17B5F9F498CFDFC232f55b8df71",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "LTC",
        ledgerId: 18,
        name: "Litecoin",
        icon: "ltc.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xf7094f76ac4abd28abcac62793e9d561c2235a0bcfaaa496b3e98f57eca2491f",
        chains: [
            {
                chainId: 8,
                code: "litecoin-testnet",
                name: "Litecoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "LTC",
                explorerUrl: "https://litecoinspace.org/testnet",
                icon: "litecoin.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 16,
                isNativeAsset: true,
                networkFee: "0.00012",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0x0DC522F091F6275880F0600AE7542faf2a975410",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "SOL",
        ledgerId: 4,
        name: "Solana",
        icon: "sol.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x62a22ed7f43907e9065ebbd4094e4ffa89985583e52d491251619a4c5b0be979",
        chains: [
            {
                chainId: 3,
                code: "solana-devnet",
                name: "Solana Devnet",
                nativeChainId: "",
                nativeCurrencySymbol: "SOL",
                explorerUrl: "https://solscan.io/?cluster=devnet",
                icon: "sol.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: true,
                minAddressLength: 32,
                maxAddressLength: 44,
                chainAssetId: 4,
                isNativeAsset: true,
                networkFee: "0.007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 9,
                },
                zToken: {
                    address: "0x201422a01e2dc561d1cDA263b42AE54e4cf462A0",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "USDC",
        ledgerId: 2,
        name: "USD Coin",
        icon: "usdc.webp",
        quantityScale: 6,
        quantityDisplayDecimals: 4,
        uAssetId: "",
        chains: [
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 7,
                isNativeAsset: false,
                networkFee: "0",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xBF3a49E67e8B6101082515aa42bBA45b3eBEBD7b",
                    decimals: 18,
                },
                zToken: {
                    address: "0xDD652c2d6C5790104BcFd611fE2a46a7481BDC9C",
                    decimals: 18,
                },
            },
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 13,
                isNativeAsset: false,
                networkFee: "0",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xb58DA92C27Df435C46170CCBFdCAF0997E23C07d",
                    decimals: 18,
                },
                zToken: {
                    address: "0x63149133896F98F43272d979A243E2C692252424",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "USDT",
        ledgerId: 1,
        name: "Tether USD",
        icon: "usdt.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 4,
        uAssetId: "0xca41b004d4133d516f2302a6a68d02d659739ecd39c702e354f6b4f4df7b8787",
        chains: [
            {
                chainId: 2,
                code: "ethereum-sepolia",
                name: "Ethereum Sepolia",
                nativeChainId: "11155111",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.etherscan.io",
                icon: "eth.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 75,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 3,
                isNativeAsset: false,
                networkFee: "0.0007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x49cf980C26D6Af2979E9dCE8662cD617a037D2fD",
                    decimals: 6,
                },
                zToken: {
                    address: "0x3989036c3b0eE27162effb85B6BcC3f7080cb716",
                    decimals: 18,
                },
            },
            {
                chainId: 3,
                code: "solana-devnet",
                name: "Solana Devnet",
                nativeChainId: "",
                nativeCurrencySymbol: "SOL",
                explorerUrl: "https://solscan.io/?cluster=devnet",
                icon: "sol.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: true,
                minAddressLength: 32,
                maxAddressLength: 44,
                chainAssetId: 5,
                isNativeAsset: false,
                networkFee: "0.58",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "Hcd9XRSAuXVzKVdYSnLNHW34zirLCfhKAWmXY179NQ9z",
                    decimals: 6,
                },
                zToken: {
                    address: "0xE154f0b828E8D78E1132060324a87d7D1599d071",
                    decimals: 18,
                },
            },
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 8,
                isNativeAsset: false,
                networkFee: "0.004",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xfCe5bA86420Ed5fD17930cE7d564941D41B1373d",
                    decimals: 18,
                },
                zToken: {
                    address: "0x9258393136fAdeB707087FDEfA3A843A10C0Dd7F",
                    decimals: 18,
                },
            },
            {
                chainId: 5,
                code: "arbitrum-sepolia",
                name: "Arbitrum Sepolia",
                nativeChainId: "421614",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.arbiscan.io",
                icon: "arb.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 10,
                isNativeAsset: false,
                networkFee: "0.013",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xc04423f2a04e80c1E47695f0ec398F168b39d118",
                    decimals: 18,
                },
                zToken: {
                    address: "0x7372c92Fd3C66bEf2bc2AABd8AFf3f63D6Fa3238",
                    decimals: 18,
                },
            },
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 14,
                isNativeAsset: false,
                networkFee: "0.17",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x062dB35dE5d1a3696bcA0CD53fd320101C335683",
                    decimals: 18,
                },
                zToken: {
                    address: "0x3Ed1cC6b2a9f81535C273e295aD436E2a98a2185",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "XRP",
        ledgerId: 17,
        name: "Ripple",
        icon: "xrp.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x449a38e45f496f53fe215fa3fcd2041abc7fd3ac76af9defce42ea241b2a5fea",
        chains: [
            {
                chainId: 9,
                code: "ripple-testnet",
                name: "Ripple Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "XRP",
                explorerUrl: "https://testnet.xrpl.org/",
                icon: "ripple.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 30,
                isCaseSensitive: true,
                minAddressLength: 25,
                maxAddressLength: 46,
                chainAssetId: 17,
                isNativeAsset: true,
                networkFee: "0.00006",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 6,
                },
                zToken: {
                    address: "0x063BAb838c316041256bcC17c0F607d59205AcDE",
                    decimals: 18,
                },
            },
        ],
    },
];

export const ZIPPER_CONTRACTS_CATALOG: ZipperChainContractConfig[] = [
    {
        name: "Disperse",
        address: "0x5d9d358fFbacB5B29a3f427D28037D5E8D2B9D30",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "Multicall3",
        address: "0xF35A6AE5408fa1356064849D0BC3855f801aa6aC",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "accountDelegateRouter",
        address: "0x476cD16fbc5A03992698422bcfC6b695eA0f6e10",
        type: "",
        description: "Account Delegate Router contract",
        version: 1,
    },
    {
        name: "depositBatchRouter",
        address: "0x1Bb3892BD91e2b84Ab9ffd196061Fc0a170BB688",
        type: "",
        description: "Deposit Batch Router contract",
        version: 1,
    },
    {
        name: "fundingAccount",
        address: "0xBfF4F6224BC10f233dDB1E61E770d9832aabC7c4",
        type: "funding",
        description: "Funding Account contract",
        version: 1,
    },
    {
        name: "guardRegistry",
        address: "0xd71F60FD6f784Cc0aD8c25441568C48705D95f64",
        type: "",
        description: "Guard Registry contract",
        version: 1,
    },
    {
        name: "internalTransferFlare",
        address: "0x2E186b0b5b3b0aA496E573c28aCc83a8a8A7b75A",
        type: "",
        description: "Internal Transfer Flare contract",
        version: 1,
    },
    {
        name: "tradingGateway",
        address: "0xD3fecf5D39131e23b6B0f872cA0a21c8A5a30932",
        type: "trading",
        description: "Trading Gateway contract",
        version: 1,
    },
    {
        name: "validationBatchRouter",
        address: "0xb4c6e583fbbc511bEC625804FBdC72577348107D",
        type: "",
        description: "Validation Batch Router contract",
        version: 1,
    },
    {
        name: "zipperEndpoint",
        address: "0xae6B981BE9B73421eB1ba5372d1A4A937d63ffFB",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryChain",
        address: "0x5E3ee633bb495442912940d88418950E406CfAf3",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryFee",
        address: "0x8236C9bA6f36E7Ace4890Ad722b07564d63cB68C",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactorySubVault",
        address: "0x512ec11246ABd36a2D9369850202E6e29113Fa10",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryToken",
        address: "0x0CB99019aD0a9b51483BB4319DC017e9c1bC41D9",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryVault",
        address: "0x417A033bC4f54b55a4D9bcF16e00fC6cdC53EAD7",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperKey",
        address: "0x7Fa63d58F8C3221E7489168D2E9C7aC70718ed9c",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperToken",
        address: "0x0CB99019aD0a9b51483BB4319DC017e9c1bC41D9",
        type: "",
        description: "",
        version: 1,
    },
];

export const ZIPPER_CONTRACT_NAMES = [
    "Disperse",
    "Multicall3",
    "accountDelegateRouter",
    "depositBatchRouter",
    "fundingAccount",
    "guardRegistry",
    "internalTransferFlare",
    "tradingGateway",
    "validationBatchRouter",
    "zipperEndpoint",
    "zipperFactoryChain",
    "zipperFactoryFee",
    "zipperFactorySubVault",
    "zipperFactoryToken",
    "zipperFactoryVault",
    "zipperKey",
    "zipperToken",
] as const;

export type ZipperContractName = (typeof ZIPPER_CONTRACT_NAMES)[number];
