// AUTO-GENERATED FILE - DO NOT EDIT
// Generated at: 2026-06-02T01:36:08.645Z
// Run `bun run scripts/generate-zipper-catalog.ts` to regenerate

import type {
    ZipperEnrichedAssetConfig,
    ZipperChainConfig,
    ZipperChainContractConfig,
} from "./zipper-catalog.js";

export const ZIPPER_CHAIN_CATALOG: ZipperChainConfig[] = [
    {
        chainId: 5,
        code: "arbitrum-sepolia",
        name: "Arbitrum Sepolia",
        nativeChainId: "421614",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.arbiscan.io",
        icon: "arb.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 4,
        code: "base-sepolia",
        name: "Base Sepolia",
        nativeChainId: "84532",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.basescan.org",
        icon: "base.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 1,
        code: "bitcoin-testnet3",
        name: "Bitcoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "BTC",
        explorerUrl: "https://mempool.space/testnet",
        icon: "btc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 110,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 10,
        code: "bitcoincash-testnet",
        name: "Bitcoin Cash Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "BCH",
        explorerUrl: "https://tbch.loping.net",
        icon: "bch.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 120,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 6,
        code: "bsc-testnet",
        name: "BNB Smart Chain Testnet",
        nativeChainId: "97",
        nativeCurrencySymbol: "BNB",
        explorerUrl: "https://testnet.bscscan.com",
        icon: "bsc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 50,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 7,
        code: "doge-testnet",
        name: "Dogecoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "DOGE",
        explorerUrl: "https://doge-testnet-explorer.qed.me",
        icon: "doge.webp",
        requiredConfirmations: 5,
        confirmationTimeSeconds: 50,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 42,
    },
    {
        chainId: 11,
        code: "ethereum-classic-testnet",
        name: "Ethereum Classic Testnet",
        nativeChainId: "63",
        nativeCurrencySymbol: "ETC",
        explorerUrl: "https://etc-mordor.blockscout.com",
        icon: "etc.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 2,
        code: "ethereum-sepolia",
        name: "Ethereum Sepolia",
        nativeChainId: "11155111",
        nativeCurrencySymbol: "ETH",
        explorerUrl: "https://sepolia.etherscan.io",
        icon: "eth.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 75,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 8,
        code: "litecoin-testnet",
        name: "Litecoin Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "LTC",
        explorerUrl: "https://litecoinspace.org/testnet",
        icon: "litecoin.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 50,
        isCaseSensitive: true,
        minAddressLength: 26,
        maxAddressLength: 62,
    },
    {
        chainId: 888168,
        code: "polyester-staging",
        name: "Polyester Staging",
        nativeChainId: "888168",
        nativeCurrencySymbol: "POL",
        explorerUrl: "https://staging.polyesterscan.com",
        icon: "polyester.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 3,
        isCaseSensitive: false,
        minAddressLength: 42,
        maxAddressLength: 42,
    },
    {
        chainId: 9,
        code: "ripple-testnet",
        name: "Ripple Testnet",
        nativeChainId: "",
        nativeCurrencySymbol: "XRP",
        explorerUrl: "https://testnet.xrpl.org/",
        icon: "ripple.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 30,
        isCaseSensitive: true,
        minAddressLength: 25,
        maxAddressLength: 46,
    },
    {
        chainId: 3,
        code: "solana-devnet",
        name: "Solana Devnet",
        nativeChainId: "",
        nativeCurrencySymbol: "SOL",
        explorerUrl: "https://solscan.io/?cluster=devnet",
        icon: "sol.webp",
        requiredConfirmations: 1,
        confirmationTimeSeconds: 60,
        isCaseSensitive: true,
        minAddressLength: 32,
        maxAddressLength: 44,
    },
];

export const ZIPPER_ASSET_CATALOG: ZipperEnrichedAssetConfig[] = [
    {
        asset: "BCH",
        ledgerId: 20,
        name: "Bitcoin Cash",
        icon: "bch.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xa97cddf4a06bc5f21aca7e7540ef9ea0ff4f8adb9d7dbd7f6c26efb3f696abe9",
        chains: [
            {
                chainId: 10,
                code: "bitcoincash-testnet",
                name: "Bitcoin Cash Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "BCH",
                explorerUrl: "https://tbch.loping.net",
                icon: "bch.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 120,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 18,
                isNativeAsset: true,
                networkFee: "0.00003",
                networkFeeTsSec: 0,
                depositMinAmount: "0.00001",
                withdrawMinAmount: "0.00001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0x75c08155A05ef19317A190Af8553512f39DC69af",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "BNB",
        ledgerId: 5,
        name: "BNB",
        icon: "bnb.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x84f284b8f96a449a73a2abd6faa45f5180a36ce1925ba9b4c9683ccaa3d1178d",
        chains: [
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 11,
                isNativeAsset: true,
                networkFee: "0.0000028",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0xDa1c35644A99775e0CFa3fBA8712C154eCD9bA0A",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "BTC",
        ledgerId: 3,
        name: "Bitcoin",
        icon: "btc.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0x4bac7d8baf3f4f429951de9baff555c2f70564c6a43361e09971ef219908703d",
        chains: [
            {
                chainId: 1,
                code: "bitcoin-testnet3",
                name: "Bitcoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "BTC",
                explorerUrl: "https://mempool.space/testnet",
                icon: "btc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 110,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 1,
                isNativeAsset: true,
                networkFee: "0.000025",
                networkFeeTsSec: 0,
                depositMinAmount: "0.00001",
                withdrawMinAmount: "0.00001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0x2BAd723ac424ef9970905bC1d9F211456a6508C4",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "DOGE",
        ledgerId: 19,
        name: "Dogecoin",
        icon: "doge.webp",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xf94adcdd39eb156b60766264ff00058b4ed540a41fcd1e3f0ef433285885f736",
        chains: [
            {
                chainId: 7,
                code: "doge-testnet",
                name: "Dogecoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "DOGE",
                explorerUrl: "https://doge-testnet-explorer.qed.me",
                icon: "doge.webp",
                requiredConfirmations: 5,
                confirmationTimeSeconds: 50,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 42,
                chainAssetId: 15,
                isNativeAsset: true,
                networkFee: "0.016",
                networkFeeTsSec: 0,
                depositMinAmount: "0.1",
                withdrawMinAmount: "0.1",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0xEB35865Cb4AA9EE74D53062c92F0B8711c02c04b",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "ETC",
        ledgerId: 21,
        name: "Ethereum Classic",
        icon: "etc.svg",
        quantityScale: 18,
        quantityDisplayDecimals: 6,
        uAssetId: "0x997997d543f68c7b77e62a13efc6e546bd2a81c2aa8769c3354422ebbbb4fba4",
        chains: [
            {
                chainId: 11,
                code: "ethereum-classic-testnet",
                name: "Ethereum Classic Testnet",
                nativeChainId: "63",
                nativeCurrencySymbol: "ETC",
                explorerUrl: "https://etc-mordor.blockscout.com",
                icon: "etc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 19,
                isNativeAsset: true,
                networkFee: "0.007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0xDA6C89C791abff42d5fF84fFF7c6364aD980de6F",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "ETH",
        ledgerId: 6,
        name: "Ethereum",
        icon: "eth.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x4f5b812789fc606be1b3b16908db13fc7a9adf7ca72641f84d75b47069d3d7f0",
        chains: [
            {
                chainId: 2,
                code: "ethereum-sepolia",
                name: "Ethereum Sepolia",
                nativeChainId: "11155111",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.etherscan.io",
                icon: "eth.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 75,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 2,
                isNativeAsset: true,
                networkFee: "0.00000006",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x0b49c0869c9Fa2480e4f68B732266a105C6881FE",
                    decimals: 18,
                },
            },
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 6,
                isNativeAsset: true,
                networkFee: "0.0000004",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x9Bebb823089A1AcD59121eF5530c6324C3cf2c3A",
                    decimals: 18,
                },
            },
            {
                chainId: 5,
                code: "arbitrum-sepolia",
                name: "Arbitrum Sepolia",
                nativeChainId: "421614",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.arbiscan.io",
                icon: "arb.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 9,
                isNativeAsset: true,
                networkFee: "0.0000012",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 18,
                },
                zToken: {
                    address: "0x1D099F4C78F81382Bea8c71fdEA68343A50671fB",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "LTC",
        ledgerId: 18,
        name: "Litecoin",
        icon: "ltc.svg",
        quantityScale: 8,
        quantityDisplayDecimals: 8,
        uAssetId: "0xf7094f76ac4abd28abcac62793e9d561c2235a0bcfaaa496b3e98f57eca2491f",
        chains: [
            {
                chainId: 8,
                code: "litecoin-testnet",
                name: "Litecoin Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "LTC",
                explorerUrl: "https://litecoinspace.org/testnet",
                icon: "litecoin.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: true,
                minAddressLength: 26,
                maxAddressLength: 62,
                chainAssetId: 16,
                isNativeAsset: true,
                networkFee: "0.00012",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 8,
                },
                zToken: {
                    address: "0xFe213EE2f4e30962186AC75FB3a5cB5C3a87ca4C",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "SOL",
        ledgerId: 4,
        name: "Solana",
        icon: "sol.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x62a22ed7f43907e9065ebbd4094e4ffa89985583e52d491251619a4c5b0be979",
        chains: [
            {
                chainId: 3,
                code: "solana-devnet",
                name: "Solana Devnet",
                nativeChainId: "",
                nativeCurrencySymbol: "SOL",
                explorerUrl: "https://solscan.io/?cluster=devnet",
                icon: "sol.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: true,
                minAddressLength: 32,
                maxAddressLength: 44,
                chainAssetId: 4,
                isNativeAsset: true,
                networkFee: "0.007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.0001",
                withdrawMinAmount: "0.0001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 9,
                },
                zToken: {
                    address: "0x25bC1545635e975C045a43080b9D08076a24D935",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "USDC",
        ledgerId: 2,
        name: "USD Coin",
        icon: "usdc.webp",
        quantityScale: 6,
        quantityDisplayDecimals: 4,
        uAssetId: "",
        chains: [
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 7,
                isNativeAsset: false,
                networkFee: "0.004",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xBF3a49E67e8B6101082515aa42bBA45b3eBEBD7b",
                    decimals: 18,
                },
                zToken: {
                    address: "0xDD652c2d6C5790104BcFd611fE2a46a7481BDC9C",
                    decimals: 18,
                },
            },
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 13,
                isNativeAsset: false,
                networkFee: "0.017",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xb58DA92C27Df435C46170CCBFdCAF0997E23C07d",
                    decimals: 18,
                },
                zToken: {
                    address: "0x63149133896F98F43272d979A243E2C692252424",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "USDT",
        ledgerId: 1,
        name: "Tether USD",
        icon: "usdt.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 4,
        uAssetId: "0xca41b004d4133d516f2302a6a68d02d659739ecd39c702e354f6b4f4df7b8787",
        chains: [
            {
                chainId: 2,
                code: "ethereum-sepolia",
                name: "Ethereum Sepolia",
                nativeChainId: "11155111",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.etherscan.io",
                icon: "eth.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 75,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 3,
                isNativeAsset: false,
                networkFee: "0.0007",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x49cf980C26D6Af2979E9dCE8662cD617a037D2fD",
                    decimals: 6,
                },
                zToken: {
                    address: "0xc4631C911bcA1fc9864f4D31795BA347C8Ed2923",
                    decimals: 18,
                },
            },
            {
                chainId: 3,
                code: "solana-devnet",
                name: "Solana Devnet",
                nativeChainId: "",
                nativeCurrencySymbol: "SOL",
                explorerUrl: "https://solscan.io/?cluster=devnet",
                icon: "sol.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: true,
                minAddressLength: 32,
                maxAddressLength: 44,
                chainAssetId: 5,
                isNativeAsset: false,
                networkFee: "0.58",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "Hcd9XRSAuXVzKVdYSnLNHW34zirLCfhKAWmXY179NQ9z",
                    decimals: 6,
                },
                zToken: {
                    address: "0x1Cc56CEeB2F5DF16B33791248149a081bc01854E",
                    decimals: 18,
                },
            },
            {
                chainId: 4,
                code: "base-sepolia",
                name: "Base Sepolia",
                nativeChainId: "84532",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.basescan.org",
                icon: "base.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 8,
                isNativeAsset: false,
                networkFee: "0.004",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xfCe5bA86420Ed5fD17930cE7d564941D41B1373d",
                    decimals: 18,
                },
                zToken: {
                    address: "0x283D83F4DBDa7F80683e2D426B7Af8390B8a1626",
                    decimals: 18,
                },
            },
            {
                chainId: 5,
                code: "arbitrum-sepolia",
                name: "Arbitrum Sepolia",
                nativeChainId: "421614",
                nativeCurrencySymbol: "ETH",
                explorerUrl: "https://sepolia.arbiscan.io",
                icon: "arb.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 60,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 10,
                isNativeAsset: false,
                networkFee: "0.013",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0xc04423f2a04e80c1E47695f0ec398F168b39d118",
                    decimals: 18,
                },
                zToken: {
                    address: "0x9e9F8010A1670C8D6769EfB1fC2BE45babAF8DEc",
                    decimals: 18,
                },
            },
            {
                chainId: 6,
                code: "bsc-testnet",
                name: "BNB Smart Chain Testnet",
                nativeChainId: "97",
                nativeCurrencySymbol: "BNB",
                explorerUrl: "https://testnet.bscscan.com",
                icon: "bsc.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 50,
                isCaseSensitive: false,
                minAddressLength: 42,
                maxAddressLength: 42,
                chainAssetId: 14,
                isNativeAsset: false,
                networkFee: "0.17",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x062dB35dE5d1a3696bcA0CD53fd320101C335683",
                    decimals: 18,
                },
                zToken: {
                    address: "0x3Eb114dff0dEc096f9F22aFaBE42a13B0e3AFF81",
                    decimals: 18,
                },
            },
        ],
    },
    {
        asset: "XRP",
        ledgerId: 17,
        name: "Ripple",
        icon: "xrp.svg",
        quantityScale: 6,
        quantityDisplayDecimals: 6,
        uAssetId: "0x449a38e45f496f53fe215fa3fcd2041abc7fd3ac76af9defce42ea241b2a5fea",
        chains: [
            {
                chainId: 9,
                code: "ripple-testnet",
                name: "Ripple Testnet",
                nativeChainId: "",
                nativeCurrencySymbol: "XRP",
                explorerUrl: "https://testnet.xrpl.org/",
                icon: "ripple.webp",
                requiredConfirmations: 1,
                confirmationTimeSeconds: 30,
                isCaseSensitive: true,
                minAddressLength: 25,
                maxAddressLength: 46,
                chainAssetId: 17,
                isNativeAsset: true,
                networkFee: "0.00006",
                networkFeeTsSec: 0,
                depositMinAmount: "0.001",
                withdrawMinAmount: "0.001",
                sourceToken: {
                    address: "0x0000000000000000000000000000000000000000",
                    decimals: 6,
                },
                zToken: {
                    address: "0xF0aC702100d18Ab40857D4141c7e76e9A62caE28",
                    decimals: 18,
                },
            },
        ],
    },
];

export const ZIPPER_CONTRACTS_CATALOG: ZipperChainContractConfig[] = [
    {
        name: "Disperse",
        address: "0x5d9d358fFbacB5B29a3f427D28037D5E8D2B9D30",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "Multicall3",
        address: "0xF35A6AE5408fa1356064849D0BC3855f801aa6aC",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "fundingAccount",
        address: "0xaf93b508eD96b6b7fbF4A7eeD5416E8C1ca8d6B6",
        type: "funding",
        description: "Funding Account contract",
        version: 1,
    },
    {
        name: "guardRegistry",
        address: "0xD398B9280091f0d7c500ca0116C8757f5a1a7A29",
        type: "",
        description: "Guard Registry contract",
        version: 1,
    },
    {
        name: "internalTransferFlare",
        address: "0x180e29BdF68e8d77602f25709Da38eA953CA7578",
        type: "",
        description: "Internal Transfer Flare contract",
        version: 1,
    },
    {
        name: "tradingGateway",
        address: "0x213c3e4E6fA46595eF46BB64b35221F9e98AEcF4",
        type: "trading",
        description: "Trading Gateway contract",
        version: 1,
    },
    {
        name: "zipperEndpoint",
        address: "0x1d154127D96AEfD0d19a4644a05530Dd0809abe7",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryChain",
        address: "0x0D25A7e8B943082B21D6c2f9D17aed425bE5F5eE",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryFee",
        address: "0x81002725952a7fAB5d0F26B193386a7a4F2aC1A1",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperFactoryVault",
        address: "0x484BC2Cc13eC4f70B44fa80271a655C3E00EAB73",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperKey",
        address: "0x8A35678B28cd5b067C652733268c282187E7225d",
        type: "",
        description: "",
        version: 1,
    },
    {
        name: "zipperToken",
        address: "0x062dB35dE5d1a3696bcA0CD53fd320101C335683",
        type: "",
        description: "",
        version: 1,
    },
];

export const ZIPPER_CONTRACT_NAMES = [
    "Disperse",
    "Multicall3",
    "fundingAccount",
    "guardRegistry",
    "internalTransferFlare",
    "tradingGateway",
    "zipperEndpoint",
    "zipperFactoryChain",
    "zipperFactoryFee",
    "zipperFactoryVault",
    "zipperKey",
    "zipperToken",
] as const;

export type ZipperContractName = (typeof ZIPPER_CONTRACT_NAMES)[number];
