export { WhiteboardService } from "./whiteboard.js";
export type {
    ArchiveWhiteboardBoardInput,
    CreateWhiteboardBoardInput,
    GetWhiteboardBoardInput,
    ListWhiteboardBoardsInput,
    MintWhiteboardJoinTokenInput,
    UpdateWhiteboardBoardAclInput,
    UpdateWhiteboardBoardInput,
    WhiteboardBoard,
    WhiteboardBoardAccess,
    WhiteboardBoardAclEntry,
    WhiteboardBoardListItem,
    WhiteboardMintJoinTokenResponse,
    WhiteboardPresencePayload,
} from "./whiteboard.js";

export {
    BoardAclEntrySchema,
    BoardAccessSchema,
    BoardAclSubjectType,
    BoardAclSubjectTypeSchema,
    BoardAudience,
    BoardAudienceSchema,
    BoardPermissionsSchema,
    BoardRole,
    BoardRoleSchema,
    BoardSchema,
    CreateBoardRequestSchema,
    CreateBoardResponseSchema,
    GetBoardRequestSchema,
    GetBoardResponseSchema,
    ListBoardsRequestSchema,
    ListBoardsResponseSchema,
    MintJoinTokenRequestSchema,
    MintJoinTokenResponseSchema,
    PresencePayloadSchema,
    UpdateBoardAclRequestSchema,
    UpdateBoardAclResponseSchema,
    UpdateBoardRequestSchema,
    UpdateBoardResponseSchema,
    ArchiveBoardRequestSchema,
    ArchiveBoardResponseSchema,
    type ArchiveBoardRequest,
    type ArchiveBoardResponse,
    type Board,
    type BoardAccess,
    type BoardAclEntry,
    type BoardAclSubjectType as BoardAclSubjectTypeValue,
    type BoardAudience as BoardAudienceValue,
    type BoardListItem,
    type BoardPermissions,
    type BoardRole as BoardRoleValue,
    type CreateBoardRequest,
    type CreateBoardResponse,
    type GetBoardRequest,
    type GetBoardResponse,
    type ListBoardsRequest,
    type ListBoardsResponse,
    type MintJoinTokenRequest,
    type MintJoinTokenResponse,
    type PresencePayload,
    type UpdateBoardAclRequest,
    type UpdateBoardAclResponse,
    type UpdateBoardRequest,
    type UpdateBoardResponse,
    WhiteboardService as WhiteboardProtoService,
} from "../../gen/collab/v1/whiteboard_pb.js";
